version: '3.9'
services:
  nginx:
    restart: always
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www
    depends_on:
      - front

  front:
    image: node:16.13.0
    restart: always
    entrypoint: ["yarn", "dev"]
    volumes:
      - ./app/front:/var/www/front
    working_dir: /var/www/front

  php:
    restart: always
    build:
      context: ./docker/php
    volumes:
      - ./app/api:/var/www/api
    working_dir: /var/www/api

  worker-api:
    restart: always
    build:
      context: ./docker/php
    entrypoint: ["php", "bin/console", "messenger:consume", "mailing", "--limit=100", "--time-limit=3600"]
    volumes:
      - ./app/api:/var/www/api
    working_dir: /var/www/api

  mailhog:
    restart: always
    build:
      context: ./docker/mailhog
    ports:
      - "8025:8025"

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    volumes:
      - ./data/db:/var/lib/postgresql/data:rw
